name: fusionclock
description: "Fusion Clock App"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.2
  rename_app: ^1.3.2
  intl: ^0.18.1
  signalr_netcore: ^0.1.7+2-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/sounds/alarms/theelevatorbossanova.mp3
